export const ACTIONS = {
    SET_PLAYER : 'SET_PLAYER',
    CHECK_USERNAME : 'CHECK_USERNAME',
    ANONYMOUS_SIGNIN : 'ANONYMOUS_SIGNIN',
    UPDATE_PLAYER_FIRESTORE: 'UPDATE_PLAYER_FIRESTORE',
    CREATE_PLAYER_FIRESTORE: 'CREATE_PLAYER_FIRESTORE',
    ADD_USER_TOKEN: 'ADD_USER_TOKEN',
    UPDATE_SCORE : 'UPDATE_SCORE',
}


export const MUTATIONS = {
    SET_PLAYER : 'SET_PLAYER',
    SET_PLAYER_ID : 'SET_PLAYER_ID',
    INCREASE_SCORE : 'INCREASE_SCORE',
    DECREASE_SCORE : 'DECREASE_SCORE',
    UPDATE_PROGRESS: 'UPDATE_PROGRESS',
}