export const ACTIONS = {
    SET_QUESTIONS : 'SET_QUESTIONS',
    FETCH_QUESTIONS : 'FETCH_QUESTIONS',
    NEXT_QUESTION_SET : 'NEXT_QUESTION_SET',
    TO_NEXT_QUESTION : 'TO_NEXT_QUESTION',
    EVALUATE_ANSWER : 'EVALUATE_ANSWER',
    UPDATE_SCORE :  'UPDATE_SCORE',
}

export const MUTATIONS = {
    SET_QUESTIONS :             'SET_QUESTIONS',
    NEXT_QUESTION_SET :         'NEXT_QUESTION_SET',
    INCREASE_SCORE :            'INCREASE_SCORE',
    DECREASE_SCORE :            'DECREASE_SCORE',
    INCREASE_QUESTION_INDEX :   'INCREASE_QUESTION_INDEX',
    RESET_QUESTION_INDEX :      'RESET_QUESTION_INDEX',
    RESET_CURRENT_SET :         'RESET_CURRENT_SET',
    SYNC_STATE: 'SYNC_STATE'

}